var config = {

    /* name of the data file; use key `csv` if data file is CSV format */
    csv: 'GOGET_Earthgenome_file2024-03-29merged.csv',
    
    /* define the column and associated values for color application */
    color: {
        field: 'status',
        values: {
            'operating': 'red',
            'in_development': 'blue',
            'discovered': 'blue',
            'shut_in': 'green',
            'decommissioned': 'green',
            'cancelled': 'green',
            'abandoned': 'grey',
            'UGS': 'grey'
        }
    },

    /* define the column and values used for the filter UI. There can be multiple filters listed. 
      Additionally a custom `label` can be defined (default is the field), 
      and `values_label` (an array matching elements in `values`)
      */
    filters: [
        {
            field: 'status',
            values: ['operating','in_development','discovered','shut_in','decommissioned','cancelled','abandoned','UGS'],
        }
    ],

    /* define the field for calculating and showing capacity along with label.
       this is defined per tracker since it varies widely */
    capacityField: 'capacity',
    capacityLabel: 'million boe/y',

    /* Labels for describing the assets */
    assetFullLabel: "Oil & Gas Extraction Areas",
    assetLabel: 'areas',

    /* the column that contains the asset name. this varies between trackers */
    nameField: 'unit_name',

    /* configure the table view, selecting which columns to show, how to label them, 
        and designated which column has the link */
    
    tableHeaders: {
        values: ['unit_name', 'operator', 'status', 'country', 'province', 'production_oil', 'production_gas', 'production_oil_year', 'production_gas_year', 'production_start_year',],
        labels: ['Extraction Area', 'Operator', 'Status','Country','Subnational unit (province/state)', 'Production - Oil (Million bbl/y)', 'Production - Gas (Million m³/y)', 'Production Year - Oil', 'Production Year - Gas', 'Production start year',],
        clickColumns: ['unit_name'],
        rightAlign: ['unit_name','discovery_year', 'fid_year', 'production_start_year', 'production_gas_year', 'production_gas', 'production_oil_year', 'production_oil', ]
    },

    /* configure the search box; 
        each label has a value with the list of fields to search. Multiple fields might be searched */
    searchFields: { 'Extraction Area': ['unit_name'], 
        'Companies': ['owner', 'operator', 'parent'],
        'Discovery Year': ['discovery_year'],
        'Production start year': ['production_start_year']
    },

    /* define fields and how they are displayed. 
      `'display': 'heading'` displays the field in large type
      `'display': 'range'` will show the minimum and maximum values.
      `'display': 'join'` will join together values with a comma separator
      `'display': 'location'` will show the fields over the detail image
      `'label': '...'` prepends a label. If a range, two values for singular and plural.
    */
    detailView: {
        'unit_name': {'display': 'heading'},
        'status': {'label': 'Status'},
        'operator': {'label': 'Operator'},
        // 'parent': {'label': 'Parent'},
        'discovery_year': {'label': 'Discovery Year'},
        'fid_year': {'label': 'FID Year'},
        'production_start_year': {'label': 'Production Start Year'},
        'production_oil_year': {'label': 'Production Year - Oil'},
        'production_gas_year': {'label': 'Production Year - Gas'},
        'production_oil': {'label': 'Production - Oil (Million bbl/y)'},
        'production_gas': {'label': 'Production - Gas (Million m³/y)'},
        'province': {'display': 'location'},
        'country': {'display': 'location'}

    } 
}

// override countries variable

var countries = {
    "Africa": [
      "Algeria",
      "Angola",
      "Benin",
      "Botswana",
      "British Indian Ocean Territory",
      "Burkina Faso",
      "Burundi",
      "Cabo Verde",
      "Cameroon",
      "Central African Republic",
      "Chad",
      "Comoros",
      "DR Congo",
      "Republic of the Congo",
      "Côte d'Ivoire",
      "Djibouti",
      "Egypt",
      "Equatorial Guinea",
      "Eritrea",
      "Eswatini",
      "Ethiopia",
      "French Southern Territories",
      "Gabon",
      "The Gambia",
      "Ghana",
      "Guinea",
      "Guinea-Bissau",
      "Kenya",
      "Lesotho",
      "Liberia",
      "Libya",
      "Madagascar",
      "Malawi",
      "Mali",
      "Mauritania",
      "Mauritius",
      "Mayotte",
      "Morocco",
      "Mozambique",
      "Namibia",
      "Niger",
      "Nigeria",
      "Réunion",
      "Rwanda",
      "Saint Helena, Ascension, and Tristan da Cunha",
      "Sao Tome and Principe",
      "Senegal",
      "Senegal-Mauritania",
      "Seychelles",
      "Sierra Leone",
      "Somalia",
      "South Africa",
      "South Sudan",
      "Sudan",
      "Tanzania",
      "Togo",
      "Tunisia",
      "Uganda",
      "Western Sahara",
      "Zambia",
      "Zimbabwe"
    ],
    "Americas": [
      "Anguilla",
      "Antigua and Barbuda",
      "Argentina",
      "Aruba",
      "Bahamas",
      "Barbados",
      "Belize",
      "Bermuda",
      "Bolivia",
      "Bonaire, Sint Eustatius, and Saba",
      "Bouvet Island",
      "Brazil",
      "Canada",
      "Cayman Islands",
      "Chile",
      "Colombia",
      "Costa Rica",
      "Cuba",
      "Curaçao",
      "Dominica",
      "Dominican Republic",
      "Ecuador",
      "El Salvador",
      "Falkland Islands",
      "French Guiana",
      "Greenland",
      "Grenada",
      "Guadeloupe",
      "Guatemala",
      "Guyana",
      "Haiti",
      "Honduras",
      "Jamaica",
      "Martinique",
      "Mexico",
      "Montserrat",
      "Nicaragua",
      "Panama",
      "Paraguay",
      "Peru",
      "Puerto Rico",
      "Saint Barthélemy",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Martin (French part)",
      "Saint Pierre and Miquelon",
      "Saint Vincent and the Grenadines",
      "Sint Maarten (Dutch part)",
      "South Georgia and the South Sandwich Islands",
      "Suriname",
      "Trinidad and Tobago",
      "Turks and Caicos Islands",
      "United States",
      "Uruguay",
      "Venezuela",
      "Virgin Islands (British)",
      "Virgin Islands (U.S.)"
    ],
    "Asia": [
      "Afghanistan",
      "Armenia",
      "Azerbaijan",
      "Azerbaijan-Turkmenistan",
      "Bahrain",
      "Bangladesh",
      "Bhutan",
      "Brunei",
      "Cambodia",
      "China",
      "China-Japan",
      "Cyprus",
      "Georgia",
      "Hong Kong",
      "India",
      "Indonesia",
      "Iran",
      "Iran-Iraq",
      "Iraq",
      "Israel",
      "Japan",
      "Jordan",
      "Kazakhstan",
      "Russia-Kazakhstan",
      "North Korea",
      "South Korea",
      "Kuwait",
      "Kuwait-Saudi Arabia",
      "Kuwait-Saudi Arabia-Iran",
      "Kyrgyzstan",
      "Laos",
      "Lebanon",
      "Macao",
      "Malaysia",
      "Maldives",
      "Mongolia",
      "Myanmar",
      "Nepal",
      "Oman",
      "Pakistan",
      "Palestine",
      "Philippines",
      "Qatar",
      "Saudi Arabia",
      "Saudi Arabia-Bahrain",
      "Saudi Arabia-Iran",
      "Singapore",
      "South China Sea",
      "Sri Lanka",
      "Syria",
      "Taiwan",
      "Tajikistan",
      "Thailand",
      "Thailand-Malaysia",
      "Timor-Leste",
      "Türkiye",
      "Turkmenistan",
      "United Arab Emirates",
      "United Arab Emirates-Iran",
      "Uzbekistan",
      "Vietnam",
      "Vietnam-Malaysia",
      "Yemen"
    ],
    "Europe": [
      "Åland Islands",
      "Albania",
      "Andorra",
      "Austria",
      "Belarus",
      "Belgium",
      "Bosnia and Herzegovina",
      "Bulgaria",
      "Croatia",
      "Czech Republic",
      "Denmark",
      "Estonia",
      "Faroe Islands",
      "Finland",
      "France",
      "Germany",
      "Gibraltar",
      "Greece",
      "Guernsey",
      "Holy See",
      "Hungary",
      "Iceland",
      "Ireland",
      "Isle of Man",
      "Italy",
      "Jersey",
      "Kosovo",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "North Macedonia",
      "Malta",
      "Moldova",
      "Monaco",
      "Montenegro",
      "Netherlands",
      "Norway",
      "Poland",
      "Portugal",
      "Romania",
      "Russia",
      "Russia-Kazakhstan",
      "San Marino",
      "Serbia",
      "Slovakia",
      "Slovenia",
      "Spain",
      "Svalbard and Jan Mayen",
      "Sweden",
      "Switzerland",
      "Ukraine",
      "United Kingdom"
    ],
    "Oceania": [
      "American Samoa",
      "Australia",
      "Christmas Island",
      "Cocos (Keeling) Islands",
      "Cook Islands",
      "Fiji",
      "French Polynesia",
      "Guam",
      "Heard Island and McDonald Islands",
      "Kiribati",
      "Marshall Islands",
      "Micronesia",
      "Nauru",
      "New Caledonia",
      "New Zealand",
      "Niue",
      "Norfolk Island",
      "Northern Mariana Islands",
      "Palau",
      "Papua New Guinea",
      "Pitcairn",
      "Samoa",
      "Solomon Islands",
      "Timor Gap",
      "Tokelau",
      "Tonga",
      "Tuvalu",
      "United States Minor Outlying Islands",
      "Vanuatu",
      "Wallis and Futuna"
    ]
  };