{
    "Asia": [
        "China",
        "Hong Kong",
        "Japan",
        "Macao",
        "Mongolia",
        "North Korea",
        "South Korea",
        "Taiwan",
        "Brunei",
        "Cambodia",
        "Indonesia",
        "Laos",
        "Malaysia",
        "Myanmar",
        "Philippines",
        "Singapore",
        "Thailand",
        "Timor-Leste",
        "Vietnam",
        "Afghanistan",
        "Iran",
        "Bangladesh",
        "Bhutan",
        "India",
        "Iran-Iraq",
        "Maldives",
        "Nepal",
        "Pakistan",
        "Sri Lanka",
        "Saudi Arabia-Bahrain",
        "Saudi Arabia-Iran",
        "United Arab Emirates-Iran",  
        "Kuwait-Saudi Arabia", 
        "Kuwait-Saudi Arabia-Iran",
        "China-Japan",
        "Thailand-Malaysia",
        "Vietnam-Malaysia",
        "Russia-Kazakhstan"

    ]

}