{
  "Africa": [
    "Algeria",
    "Angola",
    "Benin",
    "Botswana",
    "British Indian Ocean Territory",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cameroon",
    "Central African Republic",
    "Chad",
    "Comoros",
    "DR Congo",
    "Republic of the Congo",
    "Côte d'Ivoire",
    "Djibouti",
    "Egypt",
    "Equatorial Guinea",
    "Eritrea",
    "Eswatini",
    "Ethiopia",
    "French Southern Territories",
    "Gabon",
    "The Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Kenya",
    "Lesotho",
    "Liberia",
    "Libya",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Niger",
    "Nigeria",
    "Réunion",
    "Rwanda",
    "Saint Helena, Ascension, and Tristan da Cunha",
    "Sao Tome and Principe",
    "Senegal",
    "Seychelles",
    "Sierra Leone",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Sudan",
    "Tanzania",
    "Togo",
    "Tunisia",
    "Uganda",
    "Western Sahara",
    "Zambia",
    "Zimbabwe",
    "Angola-Republic of the Congo"
  ]
}


// {'Burundi;', 'Ethiopia;', 'Libya;', 'Sierra Leone;', 'Gabon;', 'Nigeria; Niger; Libya;', 'Libya; Tunisia;', 'Uganda; Tanzania;', 'Tanzania;', 'Tanzania; Kenya;', 'Eswatini;', 'Senegal;', 'Egypt;', 'Zimbabwe;', 'Angola-Republic of the Congo;', 'Niger;', 'Algeria;', 'Central African Republic;', 'South Sudan;', 'Senegal-Mauritania;', "Côte d'Ivoire;", 'Uganda;', 'Madagascar;', ';', 'Tunisia;', 'DR Congo;', 'Uganda; Kenya;', 'Algeria; Spain;', 'Republic of the Congo; Angola;', 'Eritrea;', 'Rwanda;', 'Togo;', 'Nigeria; Ghana; Togo; Benin;', 'Benin;', 'British Indian Ocean Territory;', 'Republic of the Congo;', 'Djibouti;', 'Ghana;', 'Algeria; Morocco; Spain; Portugal;', 'Tunisia; Italy;', 'Botswana;', 'Western Sahara;', 'Niger; Chad;', 'Nigeria; Niger; Algeria;', 'Nigeria;', 'Zambia;', 'Mozambique;', 'Algeria; Italy;', 'Somalia;', 'Tanzania; Zambia;', 'Djibouti; Ethiopia;', 'Guinea;', "Nigeria; Benin; Togo; Ghana; Côte d'Ivoire; Liberia; Sierra Leone; Guinea; Guinea-Bissau; The Gambia; Senegal; Mauritania; Morocco; Spain;", 'Malawi;', 'The Gambia;', 'Guinea-Bissau;', 'Egypt; Jordan; Syria; Lebanon;', 'Mali;', 'South Africa; Namibia;', 'Morocco;', 'Mauritius;', 'Mozambique; South Africa;', 'Chad;', 'Angola;', 'Israel; Egypt;', 'Equatorial Guinea;', 'Niger; Benin;', 'Sao Tome and Principe;', 'Namibia;', 'Seychelles;', 'Kenya;', 'Cabo Verde;', 'Réunion;', 'Nigeria; Equatorial Guinea;', 'Chad; Cameroon;', 'Libya; Italy;', 'Burkina Faso;', 'South Africa;', 'Sudan;', 'Lesotho;', 'Mauritania;', 'Cameroon;', 'Cyprus; Egypt;', 'Algeria; Tunisia;', 'Liberia;', 'South Sudan; Kenya;', 'Comoros;', 'Angola; Zambia;', "Ghana; Côte d'Ivoire;", 'Mayotte;', 'South Sudan; Sudan;', 'Libya; Egypt;'}