{
  "Country/Areas": [
    "Albania",
    "Algeria",
    "Austria",
    "Azerbaijan",
    "Belarus",
    "Belgium",
    "Benin",
    "Bosnia and Herzegovina",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Côte d'Ivoire",
    "Denmark",
    "Egypt",
    "Estonia",
    "Finland",
    "France",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Guinea",
    "Guinea-Bissau",
    "Hungary",
    "Iran",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jordan",
    "Kazakhstan",
    "Kosovo",
    "Latvia",
    "Liberia",
    "Libya",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Mauritania",
    "Moldova",
    "Montenegro",
    "Morocco",
    "Netherlands",
    "Nigeria",
    "North Macedonia",
    "Norway",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Sierra Leone",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Syria",
    "The Gambia",
    "Togo",
    "Tunisia",
    "Türkiye",
    "Ukraine",
    "United Kingdom"
  ]
}